version: '3'
services:  
    postges:
        container_name: postgres_data
        image: postgres:9.6
        ports: 
            - 5432:5432
        volumes: 
            - ../postgre_db/:/var/lib/postgresql/data

        env_file: ../.env