# Generated by Django 3.2.3 on 2021-07-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.ManyToManyField(db_index=True, related_name='answer_type_question', to='core.AnswerType', verbose_name='Answer Type'),
        ),
    ]
