# Generated by Django 3.2.3 on 2021-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='answer_type_question', to='core.AnswerType', verbose_name='Answer Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
