# Generated by Django 3.2.3 on 2021-08-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210712_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='redirect_url',
            field=models.CharField(default='', max_length=255, verbose_name='Redirect url'),
            preserve_default=False,
        ),
    ]
