# Generated by Django 3.2.3 on 2021-08-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='successfuly_paid',
            field=models.BooleanField(default=0, verbose_name='Successfuly Paid'),
        ),
    ]
