# Generated by Django 3.2.3 on 2021-08-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_successfuly_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_video_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='YouTube video url'),
        ),
    ]
