# Generated by Django 3.2.3 on 2021-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=1, verbose_name='is Student'),
        ),
    ]
