# Generated by Django 3.2.3 on 2021-07-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=30, null=True, verbose_name='phone number'),
        ),
    ]
