# Generated by Django 3.2.3 on 2021-07-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
